### ISSUE TITLE
Debug Client and Backend: tsc-watch path contains no backslashes

### ISSUE THREAD

**Issue by NicolasNewman** [winwiz1/crisp-react#1]
**Describe the bug**
When I attempt to run the task _Debug Client and Backend_, the subtask _Debug Backend Connected to Devserver_ throws the following error:
```
> Executing task in folder server: c:\Users\Nicolas\Desktop\Programming\crisp\crisp-react\server\node_modules\.bin\tsc.cmd -p c:\Users\Nicolas\Desktop\Programming\crisp\crisp-react\server\tsconfig.json --watch <


/usr/bin/bash: c:UsersNicolasDesktopProgrammingcrispcrisp-reactservernode_modules.bintsc.cmd: command not found
The terminal process terminated with exit code: 127

Press any key to close the terminal.
```
It appears that the path it is looking for contains no \ and is one long string. I have typescript installed locally and I've tried installing it globally through both npm and yarn.

**To Reproduce**
1. Go to the Debug tab in VSCode
2. Run task _Debug Client and Backend_
3. Observe console output for subtask _Debug Backend Connected to Devserver_

**Desktop**
 - OS: Windows 10
 - NodeJS version: v12.4.0

**Comment by winwiz1** [comment]
To fix the error change VSCode configuration and select PowerShell as the default shell to be opened in VS Code Integrated Terminal:

![image](https://user-images.githubusercontent.com/50042690/71537221-fdd4a600-296c-11ea-9cc0-afff6a0e3fa5.png)

![image](https://user-images.githubusercontent.com/50042690/71537270-a3881500-296d-11ea-9af5-d590ebe6fcba.png)

Please let me know if this fixes the issue.

Sidenote:
VSCode will add the following line
`"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",`

to the `%APPDATA%\Code\User\settings.json` file. It will affect all your projects. If you prefer, you can add this line to the `settings.json` files located under `server` and `client` subdirectories of the  `crisp-react` project instead and remove it from user-level configuration file.

**Comment by NicolasNewman** [comment]
That ended up fixing the issue. Do you think there would be any way to have it work with Git Bash as well? Or is this an issue on their end?

**Comment by winwiz1** [comment]
This is a known VS Code problem with the existing issue [35593](https://github.com/microsoft/vscode/issues/35593) and its duplicates: [38178](https://github.com/Microsoft/vscode/issues/38178) and [40907](https://github.com/microsoft/vscode/issues/40907). Currently, as Microsoft representative has [said](https://github.com/microsoft/vscode/issues/35593#issuecomment-489015180),  "there isn't a good way to deal with paths like this".

**Comment by winwiz1** [comment]
The troubleshooting advise has been provided and confirmed to fix the issue. Closing.
