### ISSUE TITLE
Server Build Confusion

### ISSUE THREAD

**Issue by brian-lagerman** [winwiz1/crisp-react#11]
I'm having trouble figuring out the build server side. I've added pg-promise for a postresql db, and I have some .sql files as queries, so far so good.

The .sql files were not getting copied to the build directory, no big surprise, so I added an additional copyfiles command to the existing copy script in the server package.json file: `"copy": "copyfiles -u 1 src/**/*.sql build && ....`.  If I debug the script, it works just fine; .sql files are where they should be.

When I run debug (VS Code) after new files/changes, "copy" doesn't seem to run, which is confusing to me because it's specified in both "prestart" and "prestart:dev". I'm running the copy script manually right now, but it feels like something isn't wired right.

**Comment by winwiz1** [comment]
When you are debugging using VS Code, you start a debugging configuration from `launch.json`.

> "copy" doesn't seem to run, which is confusing

What gets executed before a debugging configuration starts is controlled by the configuration's `preLaunchTask` setting. It points to a task (called `tsc-watch`) from `tasks.json`. This task doesn't run any npm/yarn script which explains why "copy" doesn't  run.

To get `yarn prestart` executed, update the file [tasks.json](https://github.com/winwiz1/crisp-react/blob/master/server/.vscode/tasks.json) from the [Q & A](https://github.com/winwiz1/crisp-react#q--a) section which I have updated to address this issue.

Please let me know if it addresses the issue.

**Comment by brian-lagerman** [comment]
Alright, now I feel dumb. I was updating the client's `launch.json` and `tasks.json` this whole time while debugging server side. This is my first project that makes use of a VS Code workspace, so I just reflexively opened the first `.vscode` folder I saw without paying attention. I guess it's no surprise that it works much better when you edit the correct files...

Anyway, thanks for the help; that the `tsc-watch` task doesn't exist client side clued me in instantly to my mistake.

Fantastic boilerplate by the way. Props, claps, likes all around...
